## Basic Configuration

baseurl = "http://www.ryanskerwin.com" 
builddrafts = false
canonifyurls = false
languageCode = "en-US"

contentdir = "content"
layoutdir = "layouts"
publishdir = "public"

author = "Ryan S. Kerwin"
title = "Ryan S. Kerwin"

theme = "hugo-goa"

## Hugo Built-in Features
disqusShortname = "ryanskerwin-com" # Comment out to disable Disqus.
googleAnalytics = ""
enableRobotsTXT = true

## Site Settings
[params]
author = "Ryan S. Kerwin"
intro = "Code-writing human"
description = "Co-Founder/CTO at <a href='https://www.animantis.com'>Animantis</a>."
authorimage = "ryanface.png"
dateformat = "2 Jan, 2006"

## Site Meta Settings
[params.meta]
description = "Ryan Kerwin's online presence"
keywords = "software,humor,writing"

## Social Accounts
[params.social]
github = "ryanskerwin"
linkedin = "ryanstanleykerwin"
twitter = "not_ryankerwin"
facebook = "not.ryankerwin"
google = "+RyanKerwin_not"
stackoverflow = "6680756"
email = "ryanskerwin@gmail.com"

## Extras
[params.extra]
copyright = "© 2017. Ryan S. Kerwin." 
poweredby = true
hightlightjs = true

## Main Menu
[[menu.main]]
    name = "blog"
    weight = 100
    identifier = "blog"
    url = "/blog/"
[[menu.main]]
    name = "about"
    identifier = "about"
    weight = 200
    url = "/about/"